name: fuckthebeach
favicon: null
layout_spectrum: 0.75562
typography_spectrum: 0.6721271488349885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#120c10'
    - '#7b87a0'
    - '#ba0913'
    - '#b8bbab'
  brandStrength: 0.625
  lightness: 0.8059113472700119
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
